export const gifts = [
  "Digital Hug Coupon 🤗 - A cute animated hug gift",
  "Virtual Coffee Break ☕ - A coffee e-gift card",
  "Playlist of the Day 🎵 - A curated mini playlist",
  "Motivational Quote Card 💫 - A beautifully designed quote",
  "Funny Meme Package 😂 - Collection of 3 relevant memes",
  "Virtual High Five ✋ - An animated high five",
  "Digital Flower Bouquet 💐 - Beautiful flower animation",
  "Compliment of the Day ⭐ - A personalized compliment",
  "Movie Night Suggestion 🎬 - Curated movie recommendation",
  "Recipe Card 🍪 - Simple holiday recipe",
  "Feel-Good Doodle 🎨 - Cute digital artwork",
  "Mini Meditation Guide 🧘‍♀️ - 2-minute meditation script",
  "Dad Joke of the Day 😄 - Classic dad joke",
  "Digital Sticker Pack 🌟 - Set of themed stickers",
  "Song of the Day 🎼 - Mood-lifting song recommendation",
  "Virtual Fortune Cookie 🥠 - Random positive message",
  "Mini Digital Game 🎮 - Simple browser game link",
  "Gratitude Prompt ❤️ - Daily reflection question",
  "Phone Wallpaper 📱 - Seasonal wallpaper design",
  "Self-Care Tip 🌸 - Quick wellness suggestion",
  "Virtual Dance Break 💃 - 30-second dance tutorial",
  "Digital Pet Cuddles 🐱 - Cute pet animation",
  "Positive News Story 📰 - Uplifting article link",
  "Holiday Tradition Story 🎄 - Short festive tale",
  "Christmas Eve Wish ⭐ - Special personalized message",
];
