export const gifts = [
  {
    id: 1,
    title: "Day 1",
    description: " Digital Hug Coupon 🤗 (A cute animated hug gift)",
    gifUrl: "/assets/hug.gif",
  },
  {
    id: 2,
    title: "Day 2",
    description: "Virtual Coffee Break ☕ (A coffee e-gift card)",
    gifUrl: "/assets/coffee.gif",
  },
  {
    id: 3,
    title: "Day 3",
    description: "Playlist of the Day 🎵  (A curated mini playlist)",
    gifUrl: "/assets/music.gif",
  },
  {
    id: 4,
    title: "Day 4",
    description: "Motivational Quote Card 💫  (A beautifully designed quote)",
    gifUrl: "/assets/sun.gif",
  },
  {
    id: 5,
    title: "Day 5",
    description: "Funny Meme Package 😂  (Collection of 3 relevant memes)",
    gifUrl: "/assets/memePackage.gif",
  },
  {
    id: 6,
    title: "Day 6",
    description: "Virtual High Five ✋  (An animated high five)",
    gifUrl: "/assets/highFive.gif",
  },
  {
    id: 7,
    title: "Day 7",
    description: "Digital Flower Bouquet 💐  (Beautiful flower animation)",
    gifUrl: "/assets/bouqet.gif",
  },
  {
    id: 8,
    title: "Day 8",
    description: "Compliment of the Day ⭐  (A personalized compliment)",
    gifUrl: "/assets/compliment.gif",
  },
  {
    id: 9,
    title: "Day 9",
    description: "Movie Night Suggestion 🎬  (Curated movie recommendation)",
    gifUrl: "/assets/movie.gif",
  },
  {
    id: 10,
    title: "Day 10",
    description: "Feel-Good Doodle 🎨  (Cute digital artwork)",
    gifUrl: "/assets/",
  },
  {
    id: 11,
    title: "Day 11",
    description: "Mini Meditation Guide 🧘‍♀️  (2-minute meditation script)",
    gifUrl: "/assets/meditation.gif",
  },
  {
    id: 12,
    title: "Day 12",
    description: "Dad Joke of the Day 😄  (Classic dad joke)",
    gifUrl: "/assets/dadJoke.gif",
  },
  {
    id: 13,
    title: "Day 13",
    description: "Digital Sticker Pack 🌟  (Set of themed stickers)",
    gifUrl: "/assets/stars.gif",
  },
  {
    id: 14,
    title: "Day 14",
    description: "Song of the Day 🎼  (Mood-lifting song recommendation)",
    gifUrl: "/assets/song.gif",
  },
  {
    id: 15,
    title: "Day 15",
    description: "Virtual Fortune Cookie 🥠 (Random positive message)",
    gifUrl: "/assets/fortuneCookie.gif",
  },
  {
    id: 16,
    title: "Day 16",
    description: "Mini Digital Game 🎮  (Simple browser game link)",
    gifUrl: "/assets/videoGame.gif",
  },
  {
    id: 17,
    title: "Day 17",
    description: "Gratitude Prompt ❤️  (Daily reflection question)",
    gifUrl: "/assets/gratitude.gif",
  },
  {
    id: 18,
    title: "Day 18",
    description: "Phone Wallpaper 📱  (Seasonal wallpaper design)",
    gifUrl: "/assets/wallpaper.gif",
  },
  {
    id: 19,
    title: "Day 19",
    description: "Self-Care Tip 🌸  (Quick wellness suggestion)",
    gifUrl: "/assets/selfcare.gif",
  },
  {
    id: 20,
    title: "Day 20",
    description: "Virtual Dance Break 💃  (30-second dance tutorial)",
    gifUrl: "/assets/dance.gif",
  },
  {
    id: 21,
    title: "Day 21",
    description: "Digital Pet Cuddles 🐱  (Cute pet animation)",
    gifUrl: "/assets/petCuddles.gif",
  },
  {
    id: 22,
    title: "Day 22",
    description: "Positive News Story 📰  (Uplifting article link)",
    gifUrl: "/assets/book.gif",
  },
  {
    id: 23,
    title: "Day 23",
    description: "Holiday Tradition Story 🎄  (Short festive tale)",
    gifUrl: "/assets/story.gif",
  },
  {
    id: 24,
    title: "Day 24",
    description: "Christmas Eve Wish ⭐ ( Special personalized message )",
    gifUrl: "/assets/christmas.gif",
  },
  {
    id: 25,
    title: "Day 25",
    description: "Recipe Card 🍪  (Simple holiday recipe)",
    gifUrl: "/assets/recipe.gif",
  },
];
