export const gifts = [
  {
    id: 1,
    title: "Digital Hug Coupon",
    description: "",
    gifUrl: "/assets/hug.gif",
  },
  {
    id: 2,
    title: "Virtual Coffee Break",
    description: "",
    gifUrl: "/assets/coffee.gif",
  },
  {
    id: 3,
    title: "Playlist of the Day",
    description: "",
    gifUrl: "/assets/music.gif",
  },
  {
    id: 4,
    title: "Motivational Quote Card",
    description: "",
    gifUrl: "/assets/sun.gif",
  },
  {
    id: 5,
    title: "Funny Meme Package",
    description: "",
    gifUrl: "/assets/memePackage.gif",
  },
  {
    id: 6,
    title: "Virtual High Five",
    description: "",
    gifUrl: "/assets/highFive.gif",
  },
  {
    id: 7,
    title: "Digital Flower Bouquet",
    description: "",
    gifUrl: "/assets/bouqet.gif",
  },
  {
    id: 8,
    title: "Compliment of the Day",
    description: "",
    gifUrl: "/assets/compliment.gif",
  },
  {
    id: 9,
    title: "Movie Night Suggestion",
    description: "",
    gifUrl: "/assets/movie.gif",
  },
  {
    id: 10,
    title: "Feel-Good Doodle",
    description: "",
    gifUrl: "/assets/",
  },
  {
    id: 11,
    title: "Mini Meditation Guide",
    description: "",
    gifUrl: "/assets/meditation.gif",
  },
  {
    id: 12,
    title: "Dad Joke of the Day",
    description: "",
    gifUrl: "/assets/dadJoke.gif",
  },
  {
    id: 13,
    title: "Digital Sticker Pack",
    description: "",
    gifUrl: "/assets/stars.gif",
  },
  {
    id: 14,
    title: "Song of the Day",
    description: "",
    gifUrl: "/assets/song.gif",
  },
  {
    id: 15,
    title: "Virtual Fortune Cookie",
    description: "",
    gifUrl: "/assets/fortuneCookie.gif",
  },
  {
    id: 16,
    title: "Mini Digital Game",
    description: "",
    gifUrl: "/assets/videoGame.gif",
  },
  {
    id: 17,
    title: "Gratitude Prompt",
    description: "",
    gifUrl: "/assets/gratitude.gif",
  },
  {
    id: 18,
    title: "Phone Wallpaper",
    description: "",
    gifUrl: "/assets/wallpaper.gif",
  },
  {
    id: 19,
    title: "Self-Care Tip",
    description: "",
    gifUrl: "/assets/selfcare.gif",
  },
  {
    id: 20,
    title: "Virtual Dance Break",
    description: "",
    gifUrl: "/assets/dance.gif",
  },
  {
    id: 21,
    title: "Digital Pet Cuddles",
    description: "",
    gifUrl: "/assets/petCuddles.gif",
  },
  {
    id: 22,
    title: "Positive News Story",
    description: "",
    gifUrl: "/assets/book.gif",
  },
  {
    id: 23,
    title: "Holiday Tradition Story",
    description: "",
    gifUrl: "/assets/story.gif",
  },
  {
    id: 24,
    title: "Christmas Eve Wish",
    description: "",
    gifUrl: "/assets/christmas.gif",
  },
  {
    id: 25,
    title: "Recipe Card",
    description: "",
    gifUrl: "/assets/recipe.gif",
  },
];
